#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

LC_ALL=C
local_branch="$(git rev-parse --abbrev-ref HEAD)"
valid_branch_regex="^(feature|bugfix|improvement|prerelease|release|hotfix)\/[a-zA-Z0-9._-]+$"

echo -e "===\n>> Pre-Commit Hook: Checking branch name: $local_branch"

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo -e "\n🚫 There is something wrong with your branch name."
    echo -e "\n🚫 Branch names in this project must adhere to this contract: $valid_branch_regex."
    echo -e "\n🚫 Your commit will be rejected."
    echo -e "\n🚫 You should rename your branch to a valid name and try again."

    exit 1
fi
echo -e ">> Finish checking branch name.\n==="

echo -e "===\n>> Pre-Commit Hook: Run prettier-quick"
npx pretty-quick --pattern "src/**/*.*(ts|json|html|scss)" --staged
echo -e ">> Finish prettier-quick.\n=="

echo -e "===\n>> Pre-Commit Hook: Run lint"
npm run lint
echo -e ">> Finish Run lint.\n=="
